services:
  - type: web
    name: banksha-app
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
